# Extreme Reactors 2 - mods.toml

modLoader="javafml"
loaderVersion="${loader_versionrange}"

# The license for you mod. This is mandatory metadata and allows for easier comprehension of your redistributive properties.
# Review your options at https://choosealicense.com/. All rights reserved is the default copyright stance, and is thus the default here.
license="All rights reserved"

# A URL to refer people to when problems occur with this mod
issueTrackerURL="https://github.com/ZeroNoRyouki/ExtremeReactors2"
logoFile="logo.png"

[[mods]]

	modId="bigreactors"
    version="${file.jarVersion}"
    updateJSONURL="https://raw.githubusercontent.com/ZeroNoRyouki/ExtremeReactors2/master/update.json"
	displayName="${mod_name}"	
	authors="ZeroNoRyouki"
	description="Adds large, multiblock power generation machines to Minecraft. This is a continuation of the 1.7.10 mod Big Reactors from ErogenousBeef"

[[dependencies.bigreactors]]

    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_versionrange}"
    ordering="NONE"
    side="BOTH"
	
[[dependencies.bigreactors]]

	modId="forge"
	mandatory=true
	versionRange="${forge_versionrange}"
	ordering="NONE"
	side="BOTH"

[[dependencies.bigreactors]]

    modId="zerocore"
    mandatory=true
    versionRange="${zerocore_versionrange}"
    ordering="AFTER"
    side="BOTH"
